### ISSUE TITLE
Why the argument 'replacement' is set False as default when sampling? 

### ISSUE THREAD

**Issue by WwZzz** [litian96/fair_flearn#9]
Dear author, thanks for sharing your wonderful codes.
I'm curious about the reason why the argument 'replacement' is set 'False' as default when sampling clients with proportion pk. And I've noticed that this item is usually set 'True' in other papers, like “FEDERATED LEARNING’S BLESSING: FEDAVG HAS LINEAR SPEEDUP" and "On the convergence of Fedavg on non-i.i.d. data”.
![image](https://user-images.githubusercontent.com/20792079/98634239-eb354680-235d-11eb-9755-8ff33942473a.png)
![image](https://user-images.githubusercontent.com/20792079/98634210-d9ec3a00-235d-11eb-8076-a8979293eca0.png)
 I want to know whether it matters in experiments.

**Comment by litian96** [comment]
In practice, if you don't want to select the same devices again, it is reasonable to set 'replacement=False'. It usually doesn't matter in terms of the experiments where the number of devices is large. In terms of the analysis, in order to get unbiased gradients, we can assume sampling with replacement.

**Comment by WwZzz** [comment]
Thank you for reply. I got it.
